#include<math.h>
#include<stack>
#include<map>
#include<string>
#include<variant>
#include<iostream>
#include<fstream>
#include<string>

#line 11 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 123
#define YY_END_OF_BUFFER 124
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[425] =
    {   0,
        0,    0,    0,    0,    0,    0,  124,  122,  121,   96,
       91,   87,  115,  116,  119,  117,  118,  122,  120,  103,
      103,  114,   99,   74,  101,  107,   89,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  112,   88,  113,   90,
      123,  110,  110,   98,   79,   94,   80,   77,   85,   75,
       86,   76,  106,  109,    0,   78,    0,  104,    0,    0,
      103,   92,  100,   97,  102,   93,  107,   82,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,   20,  107,
      107,  107,  107,  107,  107,  107,  107,  107,   33,  107,

      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,   81,   95,  111,    0,    0,  108,  105,
       83,   84,  107,    2,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,   30,  107,  107,  107,   35,  107,  107,
      107,   39,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,   63,  107,  107,  107,  107,  107,  107,  107,
      107,    0,  106,  107,    3,    4,  107,    6,  107,    8,

      107,  107,  107,  107,  107,  107,  107,  107,   23,   24,
      107,  107,  107,  107,  107,  107,   32,  107,   36,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,   59,  107,
      107,   62,  107,  107,  107,  107,  107,   71,  107,  107,
      107,    5,    7,  107,  107,  107,   12,   13,  107,  107,
      107,  107,  107,  107,  107,  107,  107,   28,   29,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,   50,  107,  107,  107,  107,  107,  107,
      107,   61,  107,  107,  107,   67,  107,   69,  107,  107,

       73,  107,  107,  107,  107,  107,  107,  107,  107,  107,
       19,   21,  107,  107,   26,   27,   31,   34,  107,  107,
      107,  107,  107,  107,  107,   45,  107,  107,  107,   49,
       51,   52,   53,   56,   57,  107,  107,  107,   65,  107,
      107,  107,  107,    1,  107,  107,    9,  107,  107,  107,
      107,   18,  107,  107,   37,  107,  107,   41,  107,   43,
      107,  107,  107,  107,  107,  107,  107,   64,  107,  107,
       70,  107,   10,   11,  107,  107,   16,   17,  107,   25,
      107,   40,   42,  107,   46,  107,   48,  107,  107,   58,
      107,   66,   68,   72,  107,   14,  107,   38,   44,  107,

      107,  107,  107,   15,  107,  107,  107,  107,  107,  107,
      107,  107,   55,  107,   22,  107,  107,   60,  107,   54,
      107,  107,   47,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    4,    5,    1,    6,
        7,    8,    9,    1,   10,   11,   12,   13,   14,   15,
       16,   17,   17,   18,   17,   19,   20,    1,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   28,   27,   27,
        1,    1,    1,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   27,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        3,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1,    5,    6,    7,    7,    1,    7,
        5,    5,    5,    5,    6,    5,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[434] =
    {   0,
        0,    0,    0,    0,  501,  500,  507,  510,  510,  483,
      482,   55,  510,  510,  481,   52,   53,   51,   65,   78,
      492,  510,   57,  479,   58,    0,  478,   59,   39,   70,
       68,   31,   74,  456,   74,  455,  448,   85,  452,   40,
      461,   85,   92,   56,   89,  457,  510,   62,  510,  510,
      510,  510,  482,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  106,  510,  491,  510,  134,   85,  481,    0,
      480,  467,  510,  510,  510,  466,    0,  510,  449,  445,
      437,  441,  449,   77,  452,  451,  438,  122,  430,  436,
      430,  427,   91,  435,  431,  427,  434,  423,    0,  115,

      428,  421,  427,  416,  432,  425,  430,  118,  432,  122,
      419,  105,  134,  423,  419,  127,  119,  415,  128,  420,
      411,  104,  418,  510,  510,  510,  168,  454,  510,    0,
      510,  510,  418,    0,  410,  412,  421,  416,  417,  402,
      400,  131,  406,  415,  410,  412,  412,  407,  399,  131,
      405,  391,  407,    0,  402,  392,  396,    0,  397,  402,
      397,    0,  378,  389,  382,  377,  378,  385,  386,  381,
      373,  372,  374,  377,  384,  369,  367,  367,  370,  366,
      147,  378,    0,  377,  367,  371,  366,  359,  373,  375,
      364,  170,  179,  361,    0,    0,  363,    0,  364,  186,

      353,  351,  360,  349,  347,  347,  354,  352,    0,    0,
      354,  345,  344,  355,  340,  345,    0,  344,    0,  354,
      337,  351,  338,  351,  350,  345,  340,  330,  328,  337,
      328,  325,  338,  328,  332,  337,  336,  327,    0,  336,
      314,    0,  167,  322,  327,  326,  312,    0,  312,  325,
      315,    0,    0,  340,  342,  326,    0,  173,  312,  300,
      312,  317,  316,  311,  316,  299,  304,    0,    0,  312,
      310,  303,  298,  307,  292,  291,  290,  305,  304,  287,
      300,  287,  290,    0,  298,  295,  297,  280,  290,  296,
      292,    0,  290,  290,  292,    0,  279,    0,  290,  281,

        0,  283,  288,  287,  267,  282,  261,  263,  267,  262,
        0,    0,  277,  270,    0,    0,    0,    0,  273,  276,
      261,  258,  260,  268,  253,    0,  266,  253,  264,    0,
        0,    0,  268,    0,    0,  248,  266,  259,    0,  252,
      258,  251,  250,    0,  241,  240,    0,  257,  242,  251,
      250,    0,  254,  234,    0,  249,  232,    0,  233,    0,
      244,  231,  232,  228,  176,  240,  233,    0,  238,  238,
        0,  236,    0,    0,  222,  222,    0,    0,  235,    0,
      232,    0,    0,  232,    0,  218,    0,  216,  232,    0,
      218,    0,    0,    0,  212,    0,  229,    0,    0,  224,

      210,  209,  223,    0,  207,  205,  218,  203,  220,  201,
      219,  200,    0,  191,    0,  171,  121,    0,  113,    0,
       54,   13,    0,  510,  210,  217,  222,  223,  227,  233,
      238,  239,  244
    } ;

static const flex_int16_t yy_def[434] =
    {   0,
      424,    1,  425,  425,  426,  426,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      427,  424,  424,  424,  424,  428,  424,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  429,  424,  430,  424,  424,   20,  431,  432,
      427,  424,  424,  424,  424,  424,  428,  424,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,

      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  424,  424,  424,  433,  430,  424,  432,
      424,  424,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  424,  424,  428,  428,  428,  428,  428,  428,  428,

      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,

      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,

      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,    0,  424,  424,  424,  424,  424,  424,
      424,  424,  424
    } ;

static const flex_int16_t yy_nxt[570] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   21,   21,   21,   21,   21,   21,
       22,   23,   24,   25,   26,   26,   26,   26,   27,   26,
       28,   29,   30,   31,   32,   33,   34,   26,   35,   26,
       36,   37,   38,   39,   40,   26,   41,   42,   43,   44,
       45,   46,   26,   26,   26,   47,   48,   49,   50,   56,
       59,  423,   61,   63,   63,   63,   63,   63,   63,   63,
       63,   91,   64,   92,   60,   62,   65,   57,   72,   73,
       75,   76,   82,   93,  124,   83,  108,   66,   67,  109,
       68,   68,   68,   68,   68,   68,   69,   69,  119,   79,

       84,  422,   88,  120,   94,   70,   80,   85,   81,   99,
       86,   89,  424,   87,   95,  103,  100,   96,  125,  104,
       97,   90,  111,  112,  138,  139,  115,  121,  105,  116,
       70,  127,  122,  113,  106,  150,  114,  424,  117,  151,
      127,  174,  189,  421,  190,  118,   63,   63,   63,   63,
       63,   63,   63,   63,  143,  157,  166,  144,  169,  175,
      170,  167,  145,  158,  176,  180,  185,  171,  182,  420,
      172,  211,  183,  181,  212,  186,  192,  192,  202,  203,
      177,  240,  193,  193,  193,  193,  193,  193,  193,  193,
      241,  193,  193,  193,  193,  193,  193,  193,  193,  254,

      293,  255,  306,  419,  256,  294,  388,  307,  389,  295,
       51,   51,   51,   51,   51,   51,   51,   52,   52,   52,
       52,   52,   52,   52,   71,   71,   77,   77,   77,   77,
       63,  418,   63,  128,  128,  128,  128,  128,  128,  128,
       69,   69,  130,  130,  130,  193,  417,  193,  416,  415,
      414,  413,  412,  411,  410,  409,  408,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  387,  386,  385,  384,  383,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,

      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,

      257,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      210,  209,  208,  207,  206,  205,  204,  201,  200,  199,
      198,  197,  196,  195,  194,  129,  191,  188,  187,  184,
      179,  178,  173,  168,  165,  164,  163,  162,  161,  160,
      159,  156,  155,  154,  153,  152,  149,  148,  147,  146,
      142,  141,  140,  137,  136,  135,  134,  133,  132,  131,
       67,   67,  129,  126,  123,  110,  107,  102,  101,   98,

       78,   74,   67,   58,   55,   54,  424,   53,   53,    7,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424
    } ;

static const flex_int16_t yy_chk[570] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   12,
       16,  422,   17,   18,   18,   18,   18,   18,   18,   18,
       18,   32,   19,   32,   16,   17,   19,   12,   23,   23,
       25,   25,   29,   32,   48,   29,   40,   19,   20,   40,
       20,   20,   20,   20,   20,   20,   20,   20,   44,   28,

       30,  421,   31,   44,   33,   20,   28,   30,   28,   35,
       30,   31,   68,   30,   33,   38,   35,   33,   48,   38,
       33,   31,   42,   42,   84,   84,   43,   45,   38,   43,
       20,   63,   45,   42,   38,   93,   42,   68,   43,   93,
       63,  112,  122,  419,  122,   43,   67,   67,   67,   67,
       67,   67,   67,   67,   88,  100,  108,   88,  110,  112,
      110,  108,   88,  100,  113,  116,  119,  110,  117,  417,
      110,  150,  117,  116,  150,  119,  127,  127,  142,  142,
      113,  181,  192,  192,  192,  192,  192,  192,  192,  192,
      181,  193,  193,  193,  193,  193,  193,  193,  193,  200,

      243,  200,  258,  416,  200,  243,  365,  258,  365,  243,
      425,  425,  425,  425,  425,  425,  425,  426,  426,  426,
      426,  426,  426,  426,  427,  427,  428,  428,  428,  428,
      429,  414,  429,  430,  430,  430,  430,  430,  430,  430,
      431,  431,  432,  432,  432,  433,  412,  433,  411,  410,
      409,  408,  407,  406,  405,  403,  402,  401,  400,  397,
      395,  391,  389,  388,  386,  384,  381,  379,  376,  375,
      372,  370,  369,  367,  366,  364,  363,  362,  361,  359,
      357,  356,  354,  353,  351,  350,  349,  348,  346,  345,
      343,  342,  341,  340,  338,  337,  336,  333,  329,  328,

      327,  325,  324,  323,  322,  321,  320,  319,  314,  313,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  300,
      299,  297,  295,  294,  293,  291,  290,  289,  288,  287,
      286,  285,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  256,  255,  254,  251,  250,
      249,  247,  246,  245,  244,  241,  240,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  218,  216,  215,  214,
      213,  212,  211,  208,  207,  206,  205,  204,  203,  202,

      201,  199,  197,  194,  191,  190,  189,  188,  187,  186,
      185,  184,  182,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  161,  160,  159,  157,  156,  155,  153,  152,  151,
      149,  148,  147,  146,  145,  144,  143,  141,  140,  139,
      138,  137,  136,  135,  133,  128,  123,  121,  120,  118,
      115,  114,  111,  109,  107,  106,  105,  104,  103,  102,
      101,   98,   97,   96,   95,   94,   92,   91,   90,   89,
       87,   86,   85,   83,   82,   81,   80,   79,   76,   72,
       71,   69,   65,   53,   46,   41,   39,   37,   36,   34,

       27,   24,   21,   15,   11,   10,    7,    6,    5,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "SysY.l"

#line 15 "SysY.l"
int chars=0,words=0,lines=0;
int current_column = 0;
const int N =10000;
int arrnum=0;
std::string idtable[N];//存储全部的符号
int idnum = 0;
enum Context {
    NONE,
    DECLARATION
} currentContext = NONE;
// 符号表项结构
struct SymbolTableEntry {
    std::string word;            // 单词
    std::string lexeme;          // 词素
    int line_number;             // 行号
    int column_number;           // 列号
    std::string * ptr ;//符号表指针
   // SymbolTableEntry* attribute;  // 属性
    // 在此可以添加其他属性，如类型、值等。
};
struct output{
    std::string word;            // 单词
    std::string lexeme;          // 词素
    int line_number;             // 行号
    int column_number;           // 列号
    std::variant<float,SymbolTableEntry*,std::string*,char*,int> attribute;  // 属性
}arr[N];

// 符号表类
class SymbolTable {
public:
    SymbolTable() = default; 
    SymbolTable(const SymbolTable& other) : table(other.table) {}
    // 插入一个新的词素及其符号表项
    void insert(std::string lexeme, SymbolTableEntry entry) {
        table[lexeme] = entry;
    }

    // 查询词素，返回其符号表项
    SymbolTableEntry* lookup(std::string lexeme) {
        if (table.find(lexeme) != table.end()) {
            return &table[lexeme];
        }
        return nullptr;
    }
public:
    using iterator = std::map<std::string, SymbolTableEntry>::iterator;
    using const_iterator = std::map<std::string, SymbolTableEntry>::const_iterator;

    const_iterator begin() const {
        return table.begin();
    }

    const_iterator end() const {
        return table.end();
    }

private:
    std::map<std::string, SymbolTableEntry> table;  // 符号表的内部数据结构
};

// 使用栈来管理作用域，栈顶是当前的符号表
std::stack<SymbolTable> symbolTableStack;



void printSymbolTable(const SymbolTable& table, FILE* out) {
    for (SymbolTable::const_iterator it = table.begin(); it != table.end(); ++it) {
        fprintf(out, "Lexeme: %s\n", it->first.c_str()); // it->first 是词素
        // 打印其他属性...
    }
}



struct Myset
{
    char *type;
    char *content;
    int value;
}Myset[100];
int Myset_index=0;
#line 803 "lex.yy.c"

#line 805 "lex.yy.c"

#define INITIAL 0
#define ONELINECOMMENT 1
#define COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 233 "SysY.l"

#line 1026 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 425 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 510 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 234 "SysY.l"
{ 
    fprintf(yyout, "TOKEN: ALIGNOF, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    current_column += strlen(yytext);
    arr[arrnum].word="ALIGNOF";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    arrnum++;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 243 "SysY.l"
{
    fprintf(yyout, "TOKEN: ASM, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    current_column += strlen(yytext);
    arr[arrnum].word="ASM";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    arrnum++;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 252 "SysY.l"
{
    fprintf(yyout, "TOKEN: AUTO, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    current_column += strlen(yytext);
    arr[arrnum].word="AUTO";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    arrnum++;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 262 "SysY.l"
{
    currentContext = DECLARATION;
    fprintf(yyout, "TOKEN: BOOL, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    arr[arrnum].word="BOOL";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    current_column += strlen(yytext);
    arrnum++;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 273 "SysY.l"
{
    fprintf(yyout, "TOKEN: BREAK, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    arr[arrnum].word="BREAK";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    current_column += strlen(yytext);
    arrnum++;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 283 "SysY.l"
{
    fprintf(yyout, "TOKEN: CASE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    arr[arrnum].word="CASE";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    current_column += strlen(yytext);
    arrnum++;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 293 "SysY.l"
{
    fprintf(yyout, "TOKEN: CATCH, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    arr[arrnum].word="CATCH";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    current_column += strlen(yytext);
    arrnum++;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 303 "SysY.l"
{
    currentContext = DECLARATION;
    fprintf(yyout, "TOKEN: CHAR, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    arr[arrnum].word="CHAR";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    current_column += strlen(yytext);
    arrnum++;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 314 "SysY.l"
{
    currentContext = DECLARATION;
    fprintf(yyout, "TOKEN: CHAR8_T, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    arr[arrnum].word="CHAR8_T";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    current_column += strlen(yytext);
    arrnum++;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 325 "SysY.l"
{
    currentContext = DECLARATION;
    fprintf(yyout, "TOKEN: CHAR16_T, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    arr[arrnum].word="CHAR16_T";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    current_column += strlen(yytext);
    arrnum++;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 336 "SysY.l"
{
    currentContext = DECLARATION;
    fprintf(yyout, "TOKEN: CHAR32_T, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    arr[arrnum].word="CHAR32_T";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    current_column += strlen(yytext);
    arrnum++;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 346 "SysY.l"
{
    fprintf(yyout, "TOKEN: CLASS, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    current_column += strlen(yytext);
    arr[arrnum].word = "CLASS";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 356 "SysY.l"
{
    fprintf(yyout, "TOKEN: CONST, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    current_column += strlen(yytext);
    arr[arrnum].word = "CONST";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 366 "SysY.l"
{
    fprintf(yyout, "TOKEN: CONSTEXPR, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    current_column += strlen(yytext);
    arr[arrnum].word = "CONSTEXPR";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 376 "SysY.l"
{
    fprintf(yyout, "TOKEN: CONST_CAST, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    current_column += strlen(yytext);
    arr[arrnum].word = "CONST_CAST";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 386 "SysY.l"
{
    fprintf(yyout, "TOKEN: CONTINUE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    current_column += strlen(yytext);
    arr[arrnum].word = "CONTINUE";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 396 "SysY.l"
{
    fprintf(yyout, "TOKEN: DECLTYPE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    current_column += strlen(yytext);
    arr[arrnum].word = "DECLTYPE";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 406 "SysY.l"
{
    fprintf(yyout, "TOKEN: DEFAULT, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 

    arr[arrnum].word = "DEFAULT";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
        current_column += strlen(yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 417 "SysY.l"
{
    fprintf(yyout, "TOKEN: DELETE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 

    arr[arrnum].word = "DELETE";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
        current_column += strlen(yytext);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 428 "SysY.l"
{
    fprintf(yyout, "TOKEN: DO, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    
    arr[arrnum].word = "DO";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    current_column += strlen(yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 439 "SysY.l"
{
    currentContext = DECLARATION;
    fprintf(yyout, "TOKEN: DOUBLE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 
    
    arr[arrnum].word = "DOUBLE";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    current_column += strlen(yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 451 "SysY.l"
{
    fprintf(yyout, "TOKEN: DYNAMIC_CAST, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); 

    arr[arrnum].word = "DYNAMIC_CAST";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
        current_column += strlen(yytext);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 465 "SysY.l"
{fprintf(yyout, "TOKEN: ELSE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 466 "SysY.l"
{fprintf(yyout, "TOKEN: ENUM, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 467 "SysY.l"
{fprintf(yyout, "TOKEN: EXPLICIT, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 468 "SysY.l"
{fprintf(yyout, "TOKEN: EXPORT, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 469 "SysY.l"
{fprintf(yyout, "TOKEN: EXTERN, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 470 "SysY.l"
{fprintf(yyout, "TOKEN: FALSE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 471 "SysY.l"
{currentContext = DECLARATION;fprintf(yyout, "TOKEN: FLOAT, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 472 "SysY.l"
{fprintf(yyout, "TOKEN: FOR, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 473 "SysY.l"
{fprintf(yyout, "TOKEN: FRIEND, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 474 "SysY.l"
{fprintf(yyout, "TOKEN: GOTO, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 475 "SysY.l"
{
    
    arr[arrnum].word = "IF";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    fprintf(yyout, "TOKEN: IF, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);
    current_column += strlen(yytext);
    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 485 "SysY.l"
{fprintf(yyout, "TOKEN: INLINE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 486 "SysY.l"
{
   
    arr[arrnum].word = "INT";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    currentContext = DECLARATION;fprintf(yyout, "TOKEN: INT, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);
    current_column += strlen(yytext);
    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 496 "SysY.l"
{currentContext = DECLARATION;fprintf(yyout, "TOKEN: LONG, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 497 "SysY.l"
{fprintf(yyout, "TOKEN: MUTABLE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 498 "SysY.l"
{fprintf(yyout, "TOKEN: NAMESPACE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 499 "SysY.l"
{fprintf(yyout, "TOKEN: NEW, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 500 "SysY.l"
{fprintf(yyout, "TOKEN: NOEXCEPT, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 501 "SysY.l"
{fprintf(yyout, "TOKEN: NULLPTR, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 502 "SysY.l"
{fprintf(yyout, "TOKEN: OPERATOR, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 503 "SysY.l"
{fprintf(yyout, "TOKEN: PRIVATE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 504 "SysY.l"
{fprintf(yyout, "TOKEN: PROTECTED, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 505 "SysY.l"
{fprintf(yyout, "TOKEN: PUBLIC, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 506 "SysY.l"
{fprintf(yyout, "TOKEN: REGISTER, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 507 "SysY.l"
{fprintf(yyout, "TOKEN: REINTERPRET_CAST, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 508 "SysY.l"
{fprintf(yyout, "TOKEN: REQUIRES, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 509 "SysY.l"
{
    arr[arrnum].word = "RETURN";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    fprintf(yyout, "TOKEN: RETURN, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 516 "SysY.l"
{currentContext = DECLARATION;fprintf(yyout, "TOKEN: SHORT, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 517 "SysY.l"
{fprintf(yyout, "TOKEN: SIGNED, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 518 "SysY.l"
{fprintf(yyout, "TOKEN: SIZEOF, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 519 "SysY.l"
{fprintf(yyout, "TOKEN: STATIC, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 520 "SysY.l"
{fprintf(yyout, "TOKEN: STATIC_ASSERT, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 521 "SysY.l"
{fprintf(yyout, "TOKEN: STATIC_CAST, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 522 "SysY.l"
{fprintf(yyout, "TOKEN: STRUCT, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 523 "SysY.l"
{fprintf(yyout, "TOKEN: SWITCH, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 524 "SysY.l"
{fprintf(yyout, "TOKEN: TEMPLATE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 525 "SysY.l"
{fprintf(yyout, "TOKEN: THIS, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 526 "SysY.l"
{fprintf(yyout, "TOKEN: THREAD_LOCAL, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 527 "SysY.l"
{fprintf(yyout, "TOKEN: THROW, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 528 "SysY.l"
{fprintf(yyout, "TOKEN: TRUE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 529 "SysY.l"
{fprintf(yyout, "TOKEN: TRY, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 530 "SysY.l"
{fprintf(yyout, "TOKEN: TYPEDEF, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 531 "SysY.l"
{fprintf(yyout, "TOKEN: TYPEID, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 532 "SysY.l"
{fprintf(yyout, "TOKEN: TYPENAME, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 533 "SysY.l"
{fprintf(yyout, "TOKEN: UNION, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 534 "SysY.l"
{fprintf(yyout, "TOKEN: UNSIGNED, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 535 "SysY.l"
{fprintf(yyout, "TOKEN: USING, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 536 "SysY.l"
{fprintf(yyout, "TOKEN: VIRTUAL, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 537 "SysY.l"
{fprintf(yyout, "TOKEN: VOID, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 538 "SysY.l"
{fprintf(yyout, "TOKEN: VOLATILE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 539 "SysY.l"
{fprintf(yyout, "TOKEN: WHILE, LEXEME: %s, ATTRIBUTE: Keyword\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 543 "SysY.l"
{ fprintf(yyout, "TOKEN: ASSIGN, LEXEME: %s, ATTRIBUTE: Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 544 "SysY.l"
{ fprintf(yyout, "TOKEN: PLUSASSIGN, LEXEME: %s, ATTRIBUTE: Plus Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 545 "SysY.l"
{ fprintf(yyout, "TOKEN: MINUSASSIGN, LEXEME: %s, ATTRIBUTE: Minus Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 546 "SysY.l"
{ fprintf(yyout, "TOKEN: MULTASSIGN, LEXEME: %s, ATTRIBUTE: Multiplication Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 547 "SysY.l"
{ fprintf(yyout, "TOKEN: DIVASSIGN, LEXEME: %s, ATTRIBUTE: Division Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 548 "SysY.l"
{ fprintf(yyout, "TOKEN: MODASSIGN, LEXEME: %s, ATTRIBUTE: Modulo Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 549 "SysY.l"
{ fprintf(yyout, "TOKEN: ANDASSIGN, LEXEME: %s, ATTRIBUTE: And Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 550 "SysY.l"
{ fprintf(yyout, "TOKEN: ORASSIGN, LEXEME: %s, ATTRIBUTE: Or Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 551 "SysY.l"
{ fprintf(yyout, "TOKEN: XORASSIGN, LEXEME: %s, ATTRIBUTE: Xor Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 552 "SysY.l"
{ fprintf(yyout, "TOKEN: LSHIFTASSIGN, LEXEME: %s, ATTRIBUTE: Left Shift Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 553 "SysY.l"
{ fprintf(yyout, "TOKEN: RSHIFTASSIGN, LEXEME: %s, ATTRIBUTE: Right Shift Assignment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 554 "SysY.l"
{ fprintf(yyout, "TOKEN: INCREMENT, LEXEME: %s, ATTRIBUTE: Increment Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 555 "SysY.l"
{ fprintf(yyout, "TOKEN: DECREMENT, LEXEME: %s, ATTRIBUTE: Decrement Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 556 "SysY.l"
{ fprintf(yyout, "TOKEN: BITAND, LEXEME: %s, ATTRIBUTE: Bitwise And Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 557 "SysY.l"
{ fprintf(yyout, "TOKEN: BITOR, LEXEME: %s, ATTRIBUTE: Bitwise Or Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 558 "SysY.l"
{ fprintf(yyout, "TOKEN: BITXOR, LEXEME: %s, ATTRIBUTE: Bitwise Xor Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 559 "SysY.l"
{ fprintf(yyout, "TOKEN: BITNOT, LEXEME: %s, ATTRIBUTE: Bitwise Not Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 560 "SysY.l"
{ fprintf(yyout, "TOKEN: MODULO, LEXEME: %s, ATTRIBUTE: Modulo Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 561 "SysY.l"
{ fprintf(yyout, "TOKEN: LSHIFT, LEXEME: %s, ATTRIBUTE: Left Shift Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 562 "SysY.l"
{ fprintf(yyout, "TOKEN: RSHIFT, LEXEME: %s, ATTRIBUTE: Right Shift Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 563 "SysY.l"
{ fprintf(yyout, "TOKEN: LOGAND, LEXEME: %s, ATTRIBUTE: Logical And Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 564 "SysY.l"
{ fprintf(yyout, "TOKEN: LOGOR, LEXEME: %s, ATTRIBUTE: Logical Or Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 565 "SysY.l"
{ fprintf(yyout, "TOKEN: NOT, LEXEME: %s, ATTRIBUTE: Not Operator\n", yytext); current_column += strlen(yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 568 "SysY.l"
{ fprintf(yyout, "TOKEN: EQ, LEXEME: %s, ATTRIBUTE: Equality Operator\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 569 "SysY.l"
{ fprintf(yyout, "TOKEN: NEQ, LEXEME: %s, ATTRIBUTE: Not Equal Operator\n", yytext);current_column += strlen(yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 570 "SysY.l"
{ 
    arr[arrnum].word = "LT";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    fprintf(yyout, "TOKEN: LT, LEXEME: %s, ATTRIBUTE: Less Than Operator\n", yytext);current_column += strlen(yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 577 "SysY.l"
{ fprintf(yyout, "TOKEN: LE, LEXEME: %s, ATTRIBUTE: Less Than or Equal Operator\n", yytext);current_column += strlen(yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 578 "SysY.l"
{ fprintf(yyout, "TOKEN: GT, LEXEME: %s, ATTRIBUTE: Greater Than Operator\n", yytext);current_column += strlen(yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 579 "SysY.l"
{ fprintf(yyout, "TOKEN: GE, LEXEME: %s, ATTRIBUTE: Greater Than or Equal Operator\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 581 "SysY.l"
{
    int value = strtol(yytext, NULL, 10);
    arr[arrnum].word = "DEC";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arr[arrnum].attribute=value;
    arrnum++;
    fprintf(yyout, "TOKEN: INT_CONST, LEXEME: %s, ATTRIBUTE: %d\n", yytext, value);
    words++;
    chars += strlen(yytext);
    current_column += strlen(yytext);
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 595 "SysY.l"
{
    int value = strtol(yytext, NULL, 8);
    fprintf(yyout, "TOKEN: OCT_CONST, LEXEME: %s, ATTRIBUTE: %d\n", yytext, value);
    words++;
    chars += strlen(yytext);
    current_column += strlen(yytext);
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 603 "SysY.l"
{
    int value = strtol(yytext, NULL, 16);
    fprintf(yyout, "TOKEN: HEX_CONST, LEXEME: %s, ATTRIBUTE: %d\n", yytext, value);
    words++;
    chars += strlen(yytext);
    current_column += strlen(yytext);
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 611 "SysY.l"
{
    float value = atof(yytext);
    fprintf(yyout, "TOKEN: FLOAT_CONST, LEXEME: %s, ATTRIBUTE: %f\n", yytext, value);
    words++;
    chars += strlen(yytext);
    current_column += strlen(yytext);
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 620 "SysY.l"
{

    if(symbolTableStack.empty()){
        SymbolTable newTable;
        symbolTableStack.push(newTable);
    }
    
    SymbolTableEntry* entry = nullptr;
    if (!symbolTableStack.empty()) {
        entry = symbolTableStack.top().lookup(yytext);  // 查找当前符号表中的词素
    }
    std::string * ptr;
    int flag = 0;
    for(int i=0;i<idnum;i++){
        if(idtable[i]==yytext){
            ptr=&(idtable[i]);
            flag = 1;
        }
    }
    if(flag == 0){
        idtable[idnum] = yytext;
        idnum++;
        ptr = &(idtable[idnum-1]);
    }
    SymbolTableEntry newEntry;
    if (!entry) {
        // 如果词素不存在，创建新的符号表项并插入

        newEntry.word = yytext;           // 单词也被设置为yytext
        newEntry.lexeme = yytext;
        newEntry.line_number = yylineno;  // 使用yylineno来获取当前的行号
        newEntry.column_number = current_column;
        newEntry.ptr=ptr;
        entry = &newEntry;
      //  fprintf(yyout,"newonecreated\n");
        if (!symbolTableStack.empty()) {
            symbolTableStack.top().insert(yytext, newEntry);
        }
    }
    arr[arrnum].word="ID";
    arr[arrnum].lexeme=yytext;
    arr[arrnum].column_number=current_column;
    arr[arrnum].line_number=lines;
    arr[arrnum].attribute=ptr;
    arrnum++;
    fprintf(yyout, "TOKEN: ID, LEXEME: %s, column_number:%d,ATTRIBUTE: %p \n", yytext,current_column,ptr);
    words++;
    current_column += strlen(yytext);
    chars += strlen(yytext);
}
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 672 "SysY.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 675 "SysY.l"
{BEGIN COMMENT;}
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 676 "SysY.l"
{}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 677 "SysY.l"
{BEGIN INITIAL;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 680 "SysY.l"
{
    SymbolTable newTable;
    symbolTableStack.push(newTable);
    fprintf(yyout, "TOKEN: LBRACE, LEXEME: %s, ATTRIBUTE: Left Brace\n", yytext);
    current_column += strlen(yytext);
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 687 "SysY.l"
{
    if (!symbolTableStack.empty()) {
        symbolTableStack.pop();
    }
    fprintf(yyout, "TOKEN: RBRACE, LEXEME: %s, ATTRIBUTE: Right Brace\n", yytext);
    current_column += strlen(yytext);
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 694 "SysY.l"
{ 
    arr[arrnum].word = "SEMICOLON";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    currentContext = NONE;fprintf(yyout, "TOKEN: SEMICOLON, LEXEME: %s, ATTRIBUTE: Semicolon\n", yytext);
    current_column += strlen(yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 702 "SysY.l"
{
    arr[arrnum].word = "LPAREN";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    currentContext = NONE; fprintf(yyout, "TOKEN: LPAREN, LEXEME: %s, ATTRIBUTE: Left Parenthesis\n", yytext); 
    current_column += strlen(yytext);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 710 "SysY.l"
{ 
    arr[arrnum].word = "RPAREN";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    fprintf(yyout, "TOKEN: RPAREN, LEXEME: %s, ATTRIBUTE: Right Parenthesis\n", yytext); 
    current_column += strlen(yytext);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 718 "SysY.l"
{ 
    arr[arrnum].word = "PLUS";
    arr[arrnum].lexeme = yytext;
    arr[arrnum].column_number = current_column;
    arr[arrnum].line_number = lines;
    arrnum++;
    fprintf(yyout, "TOKEN: PLUS, LEXEME: %s, ATTRIBUTE: Addition Operator\n", yytext); 
    current_column += strlen(yytext);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 726 "SysY.l"
{ fprintf(yyout, "TOKEN: MINUS, LEXEME: %s, ATTRIBUTE: Subtraction Operator\n", yytext); current_column += strlen(yytext);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 727 "SysY.l"
{ fprintf(yyout, "TOKEN: MULT, LEXEME: %s, ATTRIBUTE: Multiplication Operator\n", yytext);current_column += strlen(yytext); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 728 "SysY.l"
{ fprintf(yyout, "TOKEN: DIV, LEXEME: %s, ATTRIBUTE: Division Operator\n", yytext);current_column += strlen(yytext); }
	YY_BREAK
case 121:
/* rule 121 can match eol */
YY_RULE_SETUP
#line 730 "SysY.l"
{ lines++; current_column = 0; }  // 在这里重置列计数器
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 731 "SysY.l"
{ chars++; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 733 "SysY.l"
ECHO;
	YY_BREAK
#line 2036 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ONELINECOMMENT):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 425 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 425 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 424);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 733 "SysY.l"


int main(int argc,char **argv){

        if(argc>1){
            yyin=fopen(argv[1],"r");
            if(argc>2){ 
                yyout=fopen(argv[2],"w");
            }
        }
    yylex();
    fprintf(yyout, "------------------\n");
    fprintf(yyout, "Symbol Table:\n");
    fprintf(yyout, "------------------\n");

    while (!symbolTableStack.empty()) {
        const auto& currentTable = symbolTableStack.top(); // 获取栈顶的符号表
        // 用一个函数输出当前符号表的内容
        // 为了实现这个函数，你可能需要提供对符号表内部数据结构的访问（例如通过友元或公共方法）
        printSymbolTable(currentTable, yyout);

        symbolTableStack.pop(); // 弹出栈顶的符号表
    }

    fprintf(yyout, "------------------\n");
    fprintf(yyout, "Stats:\n");
    fprintf(yyout, "%8d%8d%8d\n", lines, words, chars);
    for(int i=0;i<arrnum;i++){
            fprintf(yyout,"id%d:%s %s %d %d %p\n",i,arr[i].word.c_str(),arr[i].lexeme.c_str(),arr[i].column_number,arr[i].line_number,arr[i].attribute);
    }

    return 0;
}
